### ISSUE TITLE
Get an error when making the application

### ISSUE THREAD

**Issue by MatthewButterfly** [eddic/fastcgipp#1]
/root/app/fastcgi++/src/sockets.cpp: In member function ‘Fastcgipp::Socket Fastcgipp::SocketGroup::poll(bool)’:
/root/app/fastcgi++/src/sockets.cpp:448:27: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
                 if(events == pollIn)

**Comment by eddic** [comment]
Can you provide the contents of your generated config.h file and some details about your operating system?
