### ISSUE TITLE
Support the Meson build system.

### ISSUE THREAD

**Issue by ikmsk10** [eddic/fastcgipp#103]
Good morning!

I have begun a project that should become some `meta-layer` part of `Yocto`, and it includes the `fastcgipp`. Currently, many projects which Yocto includes uses the modern `Meson` build system, and I'd prefer to include the meson to the `fastcgipp`.
Does it interest the to transit  `fastcgipp` to `Meson` build system? I'd like to do this work if there is someone interested.

Thanks,
Igor Kononenko.

**Comment by eddic** [comment]
Hmmm. I'm honestly not sure I'm sold on Meson quite yet. I really like CMake and I don't quite see the value in migrating away from it.
