### ISSUE TITLE
Sould not register signal handlers

### ISSUE THREAD

**Issue by Finkman** [eddic/fastcgipp#106]
Our application, using the fastcgipp lib, was no longer handling the SIGTERM signal.
After a long journey of debugging we found out, that the fastcgipp lib registers various of signal handler which overwrite our handlers.
IMHO, that's a design flaw. Signals should be handled by the process, since it is the only why the catch crucial system events and messages.

## Proposed Solution

Use concept of [RAII](https://en.wikipedia.org/wiki/Resource_acquisition_is_initialization) and handle `instance::terminate` as a part of destruction process.

**Comment by eddic** [comment]
As far as I recall the signals are not implicitly set up. The [appropriate function](https://fastcgipp.isatec.ca/classFastcgipp_1_1Manager__base.html#a5d1c62529c44f717d2e81b2629bbad56) needs to be called to setup the libraries signal handling. If you don't want to use said signal handling don't call the function.

**Comment by Finkman** [comment]
In which cases is it required to call that function.
What is it purpose and how can we figure out if we should/shouldn't or must/mustn't call `setupSignals`?

**Comment by eddic** [comment]
Well that's up to you. If your application is setting up signal handlers internally, don't call it. If you want to use the default signal handlers provided by the library, call it.
