### ISSUE TITLE
Windows systems not supported???

### ISSUE THREAD

**Issue by ZCXXX999** [eddic/fastcgipp#108]
Windows systems not supported????

**Comment by eddic** [comment]
Nope. It's "ready" for the work to be done. It should mostly be in the Sockets stuff. But It's certainly not I'll ever bother doing.

**Comment by ZCXXX999** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
