### ISSUE TITLE
Not an issue just a  question

### ISSUE THREAD

**Issue by BenKnigge** [eddic/fastcgipp#11]
If I wanted to access an environment variable like the script_name and then use that to determine which class to hand to the Fastcgipp::Manager would be the simplest way to go about doing this? I'm using v 2.1

**Comment by eddic** [comment]
The library itself does not have any internal mechanism to accomplish that but I've typically done it by having a polymorphic "script" member in the Request class that is constructed based on some environment data upon first call of response() with references to the environment and out objects. Then actual handling of the response is done by the script object itself. That way anytime Request::response() is called again it simply offloads to the "script::response()" member function.

I hope that made sense. Reading my explanation it seems a little hand-wavy but unfortunately you can't see my hands!

**Comment by BenKnigge** [comment]
Would you happen to have an example of what you're talking about laying around some place?

**Comment by eddic** [comment]
Ahh. All the code I've got like that is part of some larger projects and doesn't exactly standalone. I thought of maybe putting an example together but it just hasn't happened yet.
