### ISSUE TITLE
3.0 creating named socket fails to create file

### ISSUE THREAD

**Issue by ludyte** [eddic/fastcgipp#14]
The `FastCGIPP::SocketGroups::listen( const char*, uint, const char*, const char*)` fails 
to create a file for the socket that can be referenced by [NGINX fastcgi_pass](http://nginx.org/en/docs/http/ngx_http_fastcgi_module.html#fastcgi_pass) directive.

Start a FastCGI with the following line to create a socket ...
```
    const char* sockfilepath = "/tmp/hello.sock" ;
    manager.listen(sockfilepath,  0xffffffffUL, "nobody" ) ) ;
```

Simple NGINX config.
```
http {
   server {
        location /hello {
           fastcgi_pass unix:/tmp/hello.sock ;
        }
    }
}
```

Results in the following error.
```
2017/01/09 20:17:20 [crit] 7#7: *1 connect() to unix:/tmp/hello.sock failed (2: No such file or directory) while connecting to upstream, client: 172.17.0.1, server: localhost, request: "GET /hello HTTP/1.1", upstream: "fastcgi://unix:/tmp/hello.sock:", host: "localhost:8888"
```
... because the file is not being created.

**Comment by ludyte** [comment]
unit test - https://gist.github.com/ludyte/d75d69c17ef61cc9de63d53df0d06de1

**Comment by eddic** [comment]
Yeah I misinterpreted the unlink(2) man page. Would you be willing to try 5bdaa18 and see if it works? Sorry for the late reply. I've been out of the game.

**Comment by eddic** [comment]
I'm going to assume this is sorted.
