### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by yaochunxu** [eddic/fastcgipp#2]
Scanning dependencies of target fastcgipp
[ 20%] Building CXX object CMakeFiles/fastcgipp.dir/src/log.cpp.o
cc1plus: error: invalid option argument ‘-Og’
cc1plus: error: unrecognized command line option "-std=c++14"
cc1plus: error: unrecognized command line option "-std=c++14"
make[2]: *** [CMakeFiles/fastcgipp.dir/src/log.cpp.o] Error 1
make[1]: *** [CMakeFiles/fastcgipp.dir/all] Error 2
make: *** [all] Error 2

**Comment by eddic** [comment]
Look to me like your compiler is getting a little dated. Only a compile that fully supports C++14 will work.
