### ISSUE TITLE
Way to get Raw FCGI Params

### ISSUE THREAD

**Issue by RPGillespie6** [eddic/fastcgipp#20]
Is there a way to get the raw FCGI Parameters? Your Environment class auto-parses most of them, but it is missing a few that we use. How do I access the raw FCGI parameters of a request?

**Comment by eddic** [comment]
Yeah this is pretty legit but alas the design doesn't allow for direct access to the raw data. I'll have to mull over how special FCGI params might be accessed in a similar way to special post data. It'll be quite a bit in the future though..
