### ISSUE TITLE
fastcgi++/config.hpp not found

### ISSUE THREAD

**Issue by yideng2010** [eddic/fastcgipp#23]
When I was in vs2013 compile fastcgipp - master/examples under the helloworld, tip unable to open include file: "fastcgi++ / config. HPP" : No to the file or directory I really don't have the file view under the directory

**Comment by eddic** [comment]
I can't really speak to building in a Microsoft environment. The library doesn't actually support it.

**Comment by rockingdice** [comment]
I met the same issue when building on a Cent OS 7 system. I found the config.hpp in the build folder anyway, but not in the source code. 
Should I add it in the CMakeLists.txt file?

**Comment by Sialor** [comment]
same issue
