### ISSUE TITLE
how to get custom header 

### ISSUE THREAD

**Issue by ZhangzheBJUT** [eddic/fastcgipp#26]
using fastcigpp,i can get standard headers,such as HTTP_HOST,HTTP_COOKIE,SERVER_ADDR etc. how can i get user defined headers,such as xxx_header1,xxxx_header2 etc.

**Comment by eddic** [comment]
Unfortunately the library does not provide the ability to access non-standard header types. I've been mulling over this issue for a while but haven't actually solved it. This functionality should certainly exists... but it doesn't.
