### ISSUE TITLE
  MACOSX_RPATH is not specified

### ISSUE THREAD

**Issue by xingfeT** [eddic/fastcgipp#34]
-- Configuring done
CMake Warning (dev):
  Policy CMP0042 is not set: MACOSX_RPATH is enabled by default.  Run "cmake
  --help-policy CMP0042" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  MACOSX_RPATH is not specified for the following targets:

   fastcgipp

**Comment by eddic** [comment]
I'm going to assume the cmake work done by the illustrious @Erroneous1 has solved this particular issue.
