### ISSUE TITLE
Socket Test Fails: Unable to connect to 127.0.0.1:12229

### ISSUE THREAD

**Issue by PeteDevoy** [eddic/fastcgipp#4]
Built all okay on Ubuntu Xenial Server (x32_64) but socket tests failed.  I shut down Nginx and PHP just in case but unfortunately no difference.  Please let me know if you would like any more info...

### LastTest.log Snippit
```
3/4 Testing: Fastcgipp::Sockets
3/4 Test: Fastcgipp::Sockets
Command: "/home/peter_devoy/fastcgi++.build/sockets_test"
Directory: /home/peter_devoy/fastcgi++.build
"Fastcgipp::Sockets" start time: Apr 29 23:03 BST
Output:
----------------------------------------------------------
[error] Unable to connect to 127.0.0.1:12229
[fail] Unable to connect to server
<end of output>
Test time =   0.00 sec
----------------------------------------------------------
Test Failed.
"Fastcgipp::Sockets" end time: Apr 29 23:03 BST
"Fastcgipp::Sockets" time elapsed: 00:00:00
----------------------------------------------------------
```

**Comment by eddic** [comment]
Yeah this sounds like it might be a timing issue issue where the client thread of the test tries connecting before the server has started listening. I probably should have added some sort of condition variables or something to ensure that doesn't happen. I'll try something here.

**Comment by eddic** [comment]
Check out commit 9c747d4 and try it again.

**Comment by PeteDevoy** [comment]
Hi, thanks for the quick update :)

Unfortunately I now get this:
```
3/4 Testing: Fastcgipp::Sockets
3/4 Test: Fastcgipp::Sockets
Command: "/home/peter_devoy/fastcgi++.build/sockets_test"
Directory: /home/peter_devoy/fastcgi++.build
"Fastcgipp::Sockets" start time: Apr 30 19:36 BST 
Output:
----------------------------------------------------------
[fail] There are leftover file descriptors after they should all have been closed
<end of output>
Test time =   4.34 sec 
----------------------------------------------------------
Test Failed.
"Fastcgipp::Sockets" end time: Apr 30 19:36 BST 
"Fastcgipp::Sockets" time elapsed: 00:00:04
----------------------------------------------------------
```

Looks like it could be something simple though?

**Comment by eddic** [comment]
You know, it's not so much something I anticipated as it is something I assumed simply shouldn't happen. I likened file descriptors not being properly closed to "not good" but my method of checking likely leaves something to be desired. Can you modify to check how many are left? Simply change
```
    if(openfds() != initialFds)
        FAIL_LOG("There are leftover file descriptors after they should all "\
                "have been closed");
```
to
```
    const auto fds = openfds();
    if(fds != initialFds)
        FAIL_LOG("There are " << fds << " leftover file descriptors after they "\
                "should all have been closed");
```
and see what it says?

**Comment by PeteDevoy** [comment]
Just 1.

I also changed:
```

    ss << "/proc/" << getpid() << "/fd";

    DIR* const directory = opendir(ss.str().c_str());
```

to 

```

    ss << "/proc/" << getpid() << "/fd";

    ERROR_LOG(ss.str().c_str());

    DIR* const directory = opendir(ss.str().c_str());
```

resulting in:

```
[error] /proc/1552/fd
[error] /proc/1552/fd
[fail] There are 1 leftover file descriptors after they should all have been closed
```

**Comment by PeteDevoy** [comment]
So I a log line in here:
```
    while((file = readdir(directory)) != nullptr)
        ERROR_LOG(file->d_name);
        ++count;
```

Which gave the following, which looks like "oh, 1 extra!" until you see the error message has "0"... which makes me wonder why it printed at all...

```
[error] /proc/1684/fd
[error] .
[error] ..
[error] 0
[error] 1
[error] 2
[error] 3
[error] 4
[error] /proc/1684/fd
[error] .
[error] ..
[error] 0
[error] 1
[error] 2
[error] 3
[error] 4
[error] 5
[fail] There are 0 leftover file descriptors after they should all have been closed

```

**Comment by eddic** [comment]
Hmmm. Good bit of debugging, thanks! It looks like it is simply the OS itself cleaning up the file descriptors asynchronously. Perhaps a small std::this_thread::sleep_for() before checking how many file descriptors are still open would be the solution. What do you think?

**Comment by PeteDevoy** [comment]
Glad to help!  Unfortunately I am new to C++ so not qualified answer :(  I did think there may be some semantic error in `if(fds != initialFds)` seeing as your message says there are 0 left over file descriptors but I realise the original logic has changed from `if(openfds() != initialFds)`...

I don't really understand how count is being decremented either... given the output in #issuecomment-216062252 I would have expected the first and second calls from openfds() to return 7 & 8 respectively but from the below I see it is returning 1 & 1.

```
    const auto fds = openfds()-initialFds;

    ERROR_LOG(fds); //0
    ERROR_LOG(initialFds); //1
    //fds = 0 below so openfds() = 1

    if(fds != initialFds) //0 != 1
        FAIL_LOG("There are " << fds << " leftover file descriptors after they "\
                "should all have been closed");

```

It's all foreign to me so if you're happy the logic is sound I could try putting a sleep in before `const auto fds = openfds()-initialFds;`, if you like?

**Comment by eddic** [comment]
Yeah I'd say try a few milliseconds of sleep before that statement and see what happens. Perhaps the OS just needs a little time.

**Comment by PeteDevoy** [comment]
Unfortunately it fails even with 1 minute of sleep:

**Code**
```
int main()
{
    const auto initialFds = openfds();

    std::random_device trueRand;
    std::uniform_int_distribution<> portDist(2048, 65534);
    port = std::to_string(portDist(trueRand));

    done=false;
    std::thread serverThread(server);
    {   
        std::unique_lock<std::mutex> cvLock(cvMutex);
        cv.wait(cvLock);
    }   
    client();
    serverThread.join();

    std::this_thread::sleep_for(std::chrono::milliseconds(60000));

    const auto fds = openfds()-initialFds;
    if(fds != initialFds)
        FAIL_LOG("There are " << fds << " leftover file descriptors after they "\
                "should all have been closed");

    return 0;
}
```

**Command**
`make tests;make test;cat Testing/Temporary/LastTest.log | grep -e .fail.*`

**Output**

> [fail] There are 1 leftover file descriptors after they should all have been closed

**Comment by eddic** [comment]
Man. Qoi le fuck. I guess this has nothing at all to do with the OS taking a bit longer to clean file descriptors up at all. I am, of course, assuming that if there are file descriptors remaining, it is because they haven't been properly closed. Perhaps that assumption is incorrect? I dunno. Hmmmm. I guess the next step would be to find out which file descriptor is still open. Otherwise I supposed the check is not really important but I _feel_ as though it is. If you're feeling up for the challenge I suppose you could try and match the file descriptor number to all those that have been opened. I would suspect it is a listen socket or epoll file descriptor. Otherwise, comment out the check and move on!

**Comment by PeteDevoy** [comment]
>  Perhaps that assumption is incorrect?

I am not sure because I do not understand why count is only 1... do you know why?  I will have access to the server later so I can try and do some more debugging.

**Comment by eddic** [comment]
Yeah. I haven't the foggiest idea why only one file descriptor is left over. Obviously it means all the other hundreds of file descriptors are being properly closed. Since it is only one, that may indicate either a listen or epoll file descriptor since there is only one of each of them.

**Comment by PeteDevoy** [comment]
I really mean 'how' not 'why' I.e. if the count variable is [declared in function scope](https://github.com/eddic/fastcgipp/blob/master/tests/sockets.cpp#L327), incremented in the while loop which executes 6 or 7 times, then returned from the function, how is it only 1 and not 6 or 7?  Where along the line does it get decreased?

I have access to the server now so will have a dig anyway...

**Comment by PeteDevoy** [comment]
Maybe this will shed some light on it?

```
unsigned int openfds()
{
    std::ostringstream ss; 
    ss << "/proc/" << getpid() << "/fd";

    ERROR_LOG(ss.str().c_str());

    DIR* const directory = opendir(ss.str().c_str());
    dirent* file;
    unsigned int count = 0;
    
    ERROR_LOG("count before loop:      " << count);
    
    while((file = readdir(directory)) != nullptr)
        ERROR_LOG("count before increment: " << count << "\tfile->d_name: " << file->d_name);
        ++count;
        ERROR_LOG("count after increment:  " << count << "\tfile->d_name: " << file->d_name);


    closedir(directory);
    
    ERROR_LOG("count before return:    " << count);
    return count;
}
```

Output:
----------------------------------------------------------
[error] /proc/1435/fd
[error] count before loop:      0
[error] count before increment: 0       file->d_name: .
[error] count before increment: 0       file->d_name: ..
[error] count before increment: 0       file->d_name: 0
[error] count before increment: 0       file->d_name: 1
[error] count before increment: 0       file->d_name: 2
[error] count before increment: 0       file->d_name: 3
[error] count before increment: 0       file->d_name: 4
[error] count after increment:  1       file->d_name:
<end of output>
Test time =   0.00 sec
----------------------------------------------------------

**Comment by PeteDevoy** [comment]
Maybe this will shed some light on it?

[error] count before loop:      0
[error] count before increment: 0       file->d_name: .
[error] count before increment: 0       file->d_name: ..
[error] count before increment: 0       file->d_name: 0
[error] count before increment: 0       file->d_name: 1
[error] count before increment: 0       file->d_name: 2
[error] count before increment: 0       file->d_name: 3
[error] count before increment: 0       file->d_name: 4
[error] count after increment:  1       file->d_name: 
--
I am going to change the way the string concatenation is being done because I don't know if using << is appropriate and see what happens...

**Comment by eddic** [comment]
Hmmm. I'm pretty sure that
```
    while((file = readdir(directory)) != nullptr)
        ERROR_LOG("count before increment: " << count << "\tfile->d_name: " << file->d_name);
        ++count;
        ERROR_LOG("count after increment:  " << count << "\tfile->d_name: " << file->d_name);
```
would have to be 
```
    while((file = readdir(directory)) != nullptr)
    {
        ERROR_LOG("count before increment: " << count << "\tfile->d_name: " << file->d_name);
        ++count;
        ERROR_LOG("count after increment:  " << count << "\tfile->d_name: " << file->d_name);
    }
```
to accomplish what you're trying to accomplish. What is this python? :P

**Comment by PeteDevoy** [comment]
Haha, well, as you mention it I did think it was odd that neither the while loop nor the if statement at the bottom had braces.  I was surprised at how forgiving the compiler is having always thought that whitespace is disregarded in C++.  I now realise that it allows the termination of a condition with `;` -- bit of a gotcha for a C++ new such as myself ;)

**Comment by programmercert** [comment]
I first want to thank you for this library. I have two questions: 1.Can this work on Windows or just Linux? 2.Can it work on Apache server? I just want to know before using it. Thanks again.
