### ISSUE TITLE
exceptions.hpp not in repo

### ISSUE THREAD

**Issue by PeteDevoy** [eddic/fastcgipp#5]
Am I safe to assume from [request.hpp#L36](https://github.com/eddic/fastcgipp/blob/master/include/fastcgi++/request.hpp#L36) there should be an exceptions.hpp in https://github.com/eddic/fastcgipp/tree/master/include/fastcgi++ ?

**Comment by eddic** [comment]
Well. Actually not. I've ditched the exceptions.hpp file (and exceptions in general for this library). request.hpp still asks for it because it hasn't yet be re-done (along with manager). Only the files listed in the CMakeList.txt file are actually compilable at this point.

**Comment by PeteDevoy** [comment]
Ah!  My apologies... in my eagerness to try it out I completely forgot this "Fastcgi++ is going through a dramatic rewrite now and the master branch does not work at all." ;)
