### ISSUE TITLE
Cannot compile on Ubuntu

### ISSUE THREAD

**Issue by yuppox** [eddic/fastcgipp#59]
I am having multiple issues under Ubuntu with gcc 5.4.0.

After running _make_ and _make install_, I try to build the examples. However, I get this error:

`#error This file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options.`

I didn't see any warnings/errors prior. Is there something I am missing?

**Comment by Erroneous1** [comment]
I'm not seeing an issue with building the examples in Arch Linux. What are your build steps and version of CMake?

```
mkdir build
cd build
cmake ..
make
make examples
```

It is trying to listen on STDIN in this example. helloworld.cgi needs to be run from a webserver like Apache or (I assume) nginx. If you use the [spawn-fcgi](http://redmine.lighttpd.net/projects/spawn-fcgi/) utility you can have helloworld.cgi listen on a port or socket instead or you can accomplish the same thing by editing `examples/helloworld.cpp` and using a different `listen(...)` method.

**Comment by yuppox** [comment]
Thanks. Yeah, I should have known that it needs to run from the web server.

The cmake version is 3.13.1

My build steps were very simple:

```
cmake -DCMAKE_BUILD_TYPE=RELEASE ../fastcgi++
make
make doc
make install
make examples
```

**Comment by eddic** [comment]
Trying using `make VERBOSE=1` and post the output.
