### ISSUE TITLE
Build error: Comparison between signed and unsigned integer

### ISSUE THREAD

**Issue by susnux** [eddic/fastcgipp#6]
Compiling with GCC 5.3.1 or 6.1 on an i586 openSUSE machine the build always exits with an error:

> src/request.cpp:106:64: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
> [  108s]                                  && environment().contentLength > m_maxPostSize)
> [  108s]                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~
> [  108s] /home/abuild/rpmbuild/BUILD/fastcgi++-3.0beta/src/request.cpp: In instantiation of 'std::unique_lock<std::mutex> Fastcgipp::Request<charT>::handler() [with charT = wchar_t]':
> [  108s] /home/abuild/rpmbuild/BUILD/fastcgi++-3.0beta/src/request.cpp:58:76:   required from here
> [  108s] /home/abuild/rpmbuild/BUILD/fastcgi++-3.0beta/src/request.cpp:106:64: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]

The reason is that `contentLength` is `unsigned` and `m_maxPostSize` is `ssize_t`.
A solution would be to use size_t instead of ssize_t and use std::npos instead of -1 (ok they are quite equal ;-) ) to determine if unlimited or not.

**Comment by eddic** [comment]
Good call. Adjusted with 8e1629b44d459b98b76d751665645cae657f8e05. Thanks!
