### ISSUE TITLE
gnu example can not show the image when run with nginx

### ISSUE THREAD

**Issue by z7z8th** [eddic/fastcgipp#70]
Since there's no `PATH_INFO` param in what `nginx` send to `gnu.fcgi`. 
the following condition is always false.
https://github.com/eddic/fastcgipp/blob/f321a1d2c2a1ae44447cbb15ca813697f6093e7a/examples/gnu.cpp#L102-L104

possible solution is to use `requestUri`, since the URI is not started with `gnu.png`, so use `find()` here.
https://github.com/eddic/fastcgipp/blob/f321a1d2c2a1ae44447cbb15ca813697f6093e7a/examples/gnu.cpp#L104

possible patch:
(the cmakelist.txt change is for debian stable which still uses cmake 3.7 that does not support `target_compile_features(fastcgipp PRIVATE cxx_std_14)`,
just FYI if you're willing to make it build with cmake 3.7)

```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 99d7e0d..5031dbc 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -1,4 +1,4 @@
-cmake_minimum_required(VERSION 3.8)
+cmake_minimum_required(VERSION 3.7)
 project(fastcgi++ VERSION 3.1 LANGUAGES CXX)
 
 string(TIMESTAMP BUILD_TIME UTC)
@@ -111,7 +111,10 @@ set_target_properties(fastcgipp PROPERTIES VERSION ${PROJECT_VERSION}
 
 find_package(Threads REQUIRED)
 target_link_libraries(fastcgipp PUBLIC Threads::Threads)
-target_compile_features(fastcgipp PRIVATE cxx_std_14)
+#target_compile_features(fastcgipp PRIVATE cxx_std_14)
+set(CMAKE_CXX_STANDARD 14)
+set(CMAKE_CXX_STANDARD_REQUIRED on)
+set(CMAKE_CXX_EXTENSIONS off)
 if(UNIX)
     if(CMAKE_CXX_COMPILER_ID MATCHES "GNU" OR CMAKE_CXX_COMPILER_ID MATCHES "Clang")
         target_compile_options(fastcgipp PRIVATE -Wall -Werror -fno-omit-frame-pointer)
diff --git a/examples/gnu.cpp b/examples/gnu.cpp
index 26690e6..c9c9e5e 100644
--- a/examples/gnu.cpp
+++ b/examples/gnu.cpp
@@ -99,9 +99,7 @@ L"</html>";
     //! [Response]
        bool response()
        {
-        if(
-                environment().pathInfo.size() == 1
-                && environment().pathInfo[0] == L"gnu.png")
+        if(environment().requestUri.find(L"gnu.png") != environment().requestUri.npos)
             image();
         else
             html();

```

I've tested the patch, seem work fine.

**Comment by z7z8th** [comment]
FYI, wireshark dump of what nginx sends:

```ruby
SCRIPT_FILENAME /var/www/html/vision2/gnu.png
QUERY_STRING 
REQUEST_METHOD GET
CONTENT_TYPE
CONTENT_LENGTH
SCRIPT_NAME /vision2/gnu.png
REQUEST_URI /vision2//gnu.png
DOCUMENT_URI /vision2/gnu.png
DOCUMENT_ROOT /var/www/html
SERVER_PROTOCOL HTTP/1.1
REQUEST_SCHEME http
GATEWAY_INTERFACE CGI/1.1
SERVER_SOFTWARE nginx/1.10.3
REMOTE_ADDR ::1
REMOTE_PORT 44070
SERVER_ADDR ::1
SERVER_PORT 8000
SERVER_NAME example.com
REDIRECT_STATUS 200	
HTTP_HOST localhost:8000D
HTTP_USER_AGENT Mozilla/5.0 (X11; Linux x86_64; rv:67.0) Gecko/20100101 Firefox/67.0
HTTP_ACCEPT image/webp,*/*
HTTP_ACCEPT_LANGUAGE en-US,en;q=0.5
HTTP_ACCEPT_ENCODING gzip, deflate
HTTP_DNT 1
HTTP_CONNECTION keep-alive
HTTP_REFERER http://localhost:8000/vision2/
HTTP_COOKIE sid=0mJn1sxcuH4dqMFrbvDJ
HTTP_PRAGMA no-cache
HTTP_CACHE_CONTROL no-cache


```

**Comment by eddic** [comment]
Ah man. Nginx doesn't set the path_info variable? What the heck is that? Both Apache and lighttpd set it. Apparently we aren't the first to stumble upon this issue. Quick googling shows some fixes floating around to make Nginx send path_info over FastCGI as it should. I'm going to go ahead and assume this issue would be best sorted that way.

**Comment by z7z8th** [comment]
You're right, I found nginx has an example that set PATH_INFO for php fastcgi.
Just it takes more time to run the example, and need to debug before you can run the example correctly. I think an example should not fall in that way.
BTW, fastcgi++ is not parsing the param DOCUMENT_URI.

**Comment by eddic** [comment]
I do agree that it should not fall that way but unfortunately trying to acomodate every webservers nuances might lead to a level of code bloat I'm not comfortable with.

DOCUMENT_URI isn't parsed on it's own but it should ultimately end up [Environment::others](https://fastcgipp.isatec.ca/structFastcgipp_1_1Http_1_1Environment.html) if you need it.
