### ISSUE TITLE
mail example will fail and retry inifinitly if sender address is bad

### ISSUE THREAD

**Issue by z7z8th** [eddic/fastcgipp#71]
The example app `mail.fcgi` will inifinitly retry with bad sender address.
I found thousands of fail logs after input a bad send address, I think this might be a trouble to your server.

```log
May 05 19:17:45 aa email.fcgi[15698] [error]: Bad reply from SMTP server after MAIL: 501 <oh>: sender address must contain a domain
May 05 19:17:46 aa email.fcgi[15698] [error]: Bad reply from SMTP server after MAIL: 501 <oh>: sender address must contain a domain
...
...
May 05 19:17:46 aa email.fcgi[15698] [error]: Bad reply from SMTP server after MAIL: 501 <oh>: sender address must contain a domain
May 05 19:17:46 aa email.fcgi[15698] [error]: Bad reply from SMTP server after MAIL: 501 <oh>: sender address must contain a domain
```

**Comment by eddic** [comment]
Ah yes. It would appear that the email part is somewhat incomplete in that regard. Thanks.

**Comment by eddic** [comment]
Alright the most recent commit should fix this. Let me know.

**Comment by z7z8th** [comment]
Yes, it's retrying much slower.
BTW, will it retry forever or give up after retried several times?

**Comment by eddic** [comment]
Yeah it'll keep trying forever. My logic is that for a web application like this you'd want to keep trying until the mail server is back up to dump the queue.
