### ISSUE TITLE
pkg-config cannot find fastcgi++

### ISSUE THREAD

**Issue by HemilTheRebel** [eddic/fastcgipp#77]
I had written a small web server using this library. I used to compile the program using shell scripts and it worked because I directly linked with `-lfastcgipp`. As a part of my refactor, I want to use build systems (for obvious reasons). I chose meson which could not find fastcgi++. I learned that the pkg-config was not able to find fastcgi++. This is the output of `pkg-config --cflags --libs fastcgi++`

```
Package fastcgi++ was not found in the pkg-config search path.
Perhaps you should add the directory containing `fastcgi++.pc'
to the PKG_CONFIG_PATH environment variable
Package 'fastcgi++', required by 'virtual:world', not found
```

**Note:** The PKG_CONFIG_PATH variable is empty

A quick google search about `pkg-config fastcgi++` brings me to the [documentation](http://www.nongnu.org/fastcgipp/doc/2.1/index.html) of fastcgi++ 2.1 which states:

> A pkg-config file will be installed so you can compile against the libraries with
g++ -o script.fcgi script.cpp pkg-config –libs –cflags fastcgi++

But the documentation of 3.0 does not state that.

I installed fastcgi++ as mention in the readme without SQL support. have I done something wrong? Or is the support removed in verison 3?

**Comment by HemilTheRebel** [comment]
solved this problem using `compiler.find_library()` in meson which asks the host compiler to detect the libraries.. Is this the expected workflow?

**Comment by eddic** [comment]
It depends where you installed it of course. If you pass `-DCMAKE_INSTALL_PREFIX:PATH=/usr` to cmake it will install into /usr instead of /usr/local
