### ISSUE TITLE
How to build fastcgi++ as a static library libfastcgipp.a

### ISSUE THREAD

**Issue by bstarynk** [eddic/fastcgipp#81]
Hello,
I am not familiar with [cmake](https://cmake.org/); I just know how to run it.

I am however very familiar with Linux on the command line.

It would be nice if we could `make libfastcgipp.a` because of various C++ ABI issues on Linux (e.g. the `libstdc++.so`  could be different on my Linux laptop and on the Linux VPS I am renting).

BTW, I could soon use `libfastcgipp.so` in the http://refpersys.org/ project

Regards

-----

[Basile Starynkevitch](http://starynkevitch.net/Basile/index_en.html)
<basile@starynkevitch.net> (near Paris, France)

**Comment by eddic** [comment]
Yeah the current build definition has accommodation for building static versions of the libraries. Just pass `-DBUILD_STATIC_LIBS=true`. Hopefully this fits the bill for you and fastcgi++ finds a place in RefPerSys. Enjoy!
