### ISSUE TITLE
daemonize?

### ISSUE THREAD

**Issue by AlexeyRoza** [eddic/fastcgipp#82]
hello
there's no example of how to daemonize it?
I just want to pass requests from Nginx to fcgi-daemon through unix-socket and it should be looks like:
/clients/show/123 - do function1
/leads/show/555 - do func2
/tasks/show/333 - do func3
Is that possible?

**Comment by eddic** [comment]
Yep it's possible. I don't have any examples of it though as they are somewhat implementation specific and not specific to the library itself. I've thought of putting together an example of this but it's never happened.
