### ISSUE TITLE
Are you accepting pull requests?

### ISSUE THREAD

**Issue by stevesobol** [eddic/fastcgipp#89]
Good morning,

I've forked your repo, and I'm making some changes so that fastcgipp will run in our environment; I'm working with a client who uses FreeBSD. To comply with the terms of the LGPL, I will want to contribute my changes back to you. Are you accepting pull requests at this time?

Thanks
--Steve

**Comment by eddic** [comment]
Yeah absolutely. So long as:

- Good commit messages.
- No messy working commits.
- No big commits that just encompass a bunch of changes.

So basically if the work is clean I'm happy to pull it in.

**Comment by eddic** [comment]
Also if you rebase to the current master it'd also make my life easier. I like a nice linear changelog.

**Comment by stevesobol** [comment]
Cool, thanks.
