### ISSUE TITLE
fastcgipp and proxy

### ISSUE THREAD

**Issue by atari83** [eddic/fastcgipp#92]
Hello there,

I've a development scenario and would like to know your input about it.

Lets say, I'm using fastcgipp for implementing basic Rest service. So, the module would evaluate request parameters and could either send response error directly to client, or if validation passed then based on existing request parameters it need to forward the request to other webserver[s] (act as proxy) and deliver back the response to client.

Could you please elaborate on this ?

Thanks

**Comment by SuitespaceDev** [comment]
Simply make your standard implementation first. When conditions for proxying are met just:
- use one of the 300 series HTTP redirect [https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#300](url) 
- ..or, if proxying upstream to internal servers, just fetch the request and return the response.
