### ISSUE TITLE
CMake PostgreSQL missing required version number

### ISSUE THREAD

**Issue by laifuchicago** [eddic/fastcgipp#93]
To Author:
When I used make command, it got the following error. Do you have any idea? Thanks.

![Selection_004](https://user-images.githubusercontent.com/8537280/110906779-66782a80-8347-11eb-9690-e205114a345c.png)

Jonathan Sung

**Comment by eddic** [comment]
What version of PostgreSQL are you running?

**Comment by laifuchicago** [comment]
To Author:
Version 9.5

Jonathan Sung

**Comment by eddic** [comment]
Yeah. I believe version ten at minimum is required. This really needs to be added to CMakeLists.txt. I'll leave this open as a reminder.

**Comment by eddic** [comment]
"Fixed" with b1ff6d67586cef6ebd57a4b0f2900d5ee16eb1cd
