### ISSUE TITLE
Permission not being set on unix socket according to permission parameter in listen() call.

### ISSUE THREAD

**Issue by mfvargo** [eddic/fastcgipp#97]
I'm trying to avoid using sudo and changing my apps user/group.  Even when I explicitly pass 0xffffffffUL to listen the socket file that is created does not have the correct permissions.  I end up having to pass in the user and group in order for the socket to be accessible.

```
int main(int argc, char* argv[])
{
    Fastcgipp::Manager<Echo> manager;
    //! [Manager]
    //! [Signals]
    manager.setupSignals();
    //! [Signals]
    //! [Listen]
    manager.listen("/tmp/rtjambox.sock", 0xffffffffUL); // , "www-data", "www-data");
    //! [Listen]
    //! [Start]
    manager.start();
    //! [Start]
    //! [Join]
    manager.join();

    return 0;
}
```
Results in this unix socket:
```
pi@raspberrypi:~/projects/rtjam $ ls -l /tmp/rtjambox.sock 
srwxr-xr-x 1 pi pi 0 Mar 26 12:00 /tmp/rtjambox.sock
```
and nginx cannot read that
```
2021/03/26 11:57:52 [crit] 21363#21363: *10 connect() to unix:/tmp/rtjambox.sock failed (13: Permission denied) while connecting to upstream, client: 192.168.1.245, server: _, request: "GET /rtjambox HTTP/1.1", upstream: "fastcgi://unix:/tmp/rtjambox.sock:", host: "music.basscleftech.com"
```
I was expecting to have "srwxrwxrwx" for the socket permission.  Is this a umask issue?

I have a workaround which is to add the user/group args to listen but then I have to sudo run my app for that to work.  I suppose I could run it as the www-data user as well.  I was just hoping that setting the permissions on the socket would make it work.

note:  If after the app has started and created the socket, if I 
```
$ sudo chmod 777 /tmp/rtjambox.sock
```
then nginx can talk to the fastcgi app without any problem.

**Comment by eddic** [comment]
Yeah that's weird. I've got a call that's like
```
manager.listen("/tmp/rtjambox.sock", 0666);
```
and it doesn't give me any hassle.

**Comment by mfvargo** [comment]
Well, that works.  I was just guessing based on the default that 0xffffffffUL would be the same as 0777.   0666 works great.  No more sudo.

I will close this ticket.  I think a note in the doc could help.
